site_name: 我的技术知识库
site_url: https://0richalcos.github.io/Note/
repo_url: https://github.com/0richalcos/Note
edit_uri: edit/main/Markdown/ 

# 关键配置：指定你的笔记所在的文件夹名字
docs_dir: 'Markdown' 
# 禁止生成目录式 URL (Pretty URLs)
use_directory_urls: false

# 主题
theme:
  name: material
  language: zh
  features:
    - navigation.top           # 回到顶部按钮
    - navigation.indexes    # 允许点击文件夹查看 index.md
    - navigation.tracking    # 滚动正文时，左侧/右侧导航自动跟随高亮
  palette: 
    - scheme: default
      primary: teal         
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: 切换亮色模式

# 引入 CSS
extra_css:
  - _stylesheets/extra.css 

# 引入 JS
extra_javascript:
  - _javascripts/auto_title.js

# 必装插件
plugins:
  - search
  - awesome-pages:         
      filename: .pages
      collapse_single_pages: true
  - callouts

# Markdown 渲染增强
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 1-6  # 强制大纲抓取 H1 到 H3
  - admonition             
  - pymdownx.details       
  - pymdownx.highlight     
  - pymdownx.superfences   
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg